id: IE62762D6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:27:07+00:00'
last_modified: '2022-06-09T04:52:25.295416+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17742
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་ས་བཅད་ཕྱོགས་བསྡུས་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B118:
      image_group_id: I8LS17760
      title: Volume 1 of rgyal sras lag len gyi sa bcad phyogs bsdus/
      total_pages: 54
      order: 1
      base_file: B118.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
