id: P007099
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17742
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་ས་བཅད་ཕྱོགས་བསྡུས་སོགས།
  author: ''
  volumes:
    07092eab36514685a548cfa475f5b340:
      image_group_id: I8LS17760
      title: ''
      volume_number: 1
      total_pages: 54
ebook_metadata:
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་ས་བཅད་ཕྱོགས་བསྡུས་སོགས།
  author: ''
  sku: P007099
  cover: cover.jpg
  layers:
  - pagination
