id: P007099
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:35.331163
source_metadata:
  id: bdr:W8LS17742
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་ས་བཅད་ཕྱོགས་བསྡུས་སོགས།
  author: ''
  volumes:
    048aec33f14049e08ab7b103a032018a:
      image_group_id: I8LS17760
      title: Volume 1 of rgyal sras lag len gyi sa bcad phyogs bsdus/
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
